---
-   name: Create Jenkins ssh directory
    file:
        state: directory
        path: /var/lib/jenkins/.ssh
        owner: jenkins
        group: jenkins
        mode: 0700

-   name: Install Jenkins ssh files
    copy:
        src: '{{item}}'
        dest: '/var/lib/jenkins/.ssh/{{item}}'
        owner: jenkins
        group: jenkins
        mode: 0400
    with_items:
    -   id_rsa
    -   id_rsa.pub
    -   known_hosts

-   name: Install Jenkins Slack plugin v1.8
    copy:
        src: slack.hpi
        dest: /var/lib/jenkins/plugins/slack.hpi
        owner: jenkins
        group: jenkins
        mode: 0600
    notify: restart jenkins

-   name: Install Jenkins Job Builder plugin for Slack
    pip:
        name: jenkins-jobs-slack

-   name: Create Jenkins jobs
    template:
        dest: "{{jenkins_job_builder_file_jobs_dest}}/{{item}}"
        src: "jobs/{{item}}"
    with_items:
    -   test-ci-integration.yml

-   name: Force Jenkins to reload jobs list
    command: /bin/true
    notify:
    -   Check jenkins
    -   Reload jenkins-jobs
