-   job:
    name: test-ci-integrations
    display-name: 'CI Integrations Playground'

    scm:
    -   git:
            url: git@github.com:201created/test-ci-integrations.git
            branches:
            -   origin/master

    triggers:
    -   github

    builders:
    -   github-notifier
    -   shell:
            cmd: sh test.sh

    properties:
    -   slack:
            notify-start: yes
            notify-success: yes
            notify-aborted: yes
            notify-notbuilt: yes
            notify-unstable: yes
            notify-failure: yes
            notify-backtonormal: yes
            notify-repeatedfailure: yes
            include-test-summary: yes
            show-commit-list: yes
            room: '#testing'

    publishers:
    -   github-notifier
    -   slack:
            team-domain: {{slack_domain}}
            auth-token: {{slack_auth_token}}
            build-server-url: {{ci_server_url}}

-   job:
    name: test-ci-integrations-prs
    display-name: 'CI Integrations Playground Pull Requests'

    scm:
    -   git:
            url: git@github.com:201created/test-ci-integrations.git
            choosing-strategy: inverse
            branches:
                -   origin/master

    triggers:
    -   github

    builders:
    -   github-notifier
    -   shell:
            cmd: sh test.sh

    properties:
    -   slack:
            notify-start: yes
            notify-success: yes
            notify-aborted: yes
            notify-notbuilt: yes
            notify-unstable: yes
            notify-failure: yes
            notify-backtonormal: yes
            notify-repeatedfailure: yes
            include-test-summary: yes
            show-commit-list: yes
            room: '#testing'

    publishers:
    -   github-notifier
    -   slack
