---
-   hosts: jenkins
    user: ubuntu
    become: yes
    become_method: sudo

    vars_files:
    -   vars/jenkins.yml
    -   vars/slack.vars.yml

    roles:
    -   geerlingguy.java
    -   geerlingguy.jenkins
    -   openstack.jenkins-job-builder
    -   jenkins
